"""Generates Markdown documentation for a MySQL database schema."""

from app.services import mysql_service


def generate_schema_markdown(
    host: str, port: int, user: str, password: str, database: str
) -> str:
    tables = mysql_service.list_tables(host, port, user, password, database)
    lines: list[str] = []

    lines.append(f"# Database Schema: `{database}`\n")
    lines.append(f"> Generated by WowDB · {len(tables)} table(s)\n")
    lines.append("---\n")

    lines.append("## Tables\n")
    lines.append("| Table | Engine | Approx. Rows | Comment |")
    lines.append("|---|---|---|---|")
    for t in tables:
        name = t.get("TABLE_NAME", "")
        engine = t.get("ENGINE", "—")
        rows = t.get("TABLE_ROWS", "—")
        comment = t.get("TABLE_COMMENT", "") or ""
        lines.append(f"| `{name}` | {engine} | {rows} | {comment} |")

    lines.append("")

    for t in tables:
        table_name = t.get("TABLE_NAME", "")
        detail = mysql_service.describe_table(host, port, user, password, database, table_name)

        lines.append(f"---\n\n## `{table_name}`\n")

        comment = (t.get("TABLE_COMMENT") or "").strip()
        if comment:
            lines.append(f"_{comment}_\n")

        # Columns
        lines.append("### Columns\n")
        lines.append("| Column | Type | Nullable | Key | Default | Extra |")
        lines.append("|---|---|---|---|---|---|")
        for col in detail.get("columns", []):
            col_name = col.get("COLUMN_NAME", "")
            col_type = col.get("COLUMN_TYPE", "")
            nullable = col.get("IS_NULLABLE", "")
            key = col.get("COLUMN_KEY", "") or "—"
            default = col.get("COLUMN_DEFAULT", "") or "—"
            extra = col.get("EXTRA", "") or "—"
            lines.append(f"| `{col_name}` | `{col_type}` | {nullable} | {key} | {default} | {extra} |")

        # Indexes
        indexes = detail.get("indexes", [])
        if indexes:
            lines.append("\n### Indexes\n")
            lines.append("| Name | Unique | Column | Type |")
            lines.append("|---|---|---|---|")
            seen: set[str] = set()
            for idx in indexes:
                key = f"{idx.get('INDEX_NAME')}-{idx.get('COLUMN_NAME')}"
                if key in seen:
                    continue
                seen.add(key)
                name = idx.get("INDEX_NAME", "")
                unique = "No" if idx.get("NON_UNIQUE") else "Yes"
                col = idx.get("COLUMN_NAME", "")
                itype = idx.get("INDEX_TYPE", "")
                lines.append(f"| `{name}` | {unique} | `{col}` | {itype} |")

        # Foreign keys
        fks = detail.get("foreign_keys", [])
        if fks:
            lines.append("\n### Foreign Keys\n")
            lines.append("| Constraint | Column | References |")
            lines.append("|---|---|---|")
            for fk in fks:
                constraint = fk.get("CONSTRAINT_NAME", "")
                col = fk.get("COLUMN_NAME", "")
                ref_table = fk.get("REFERENCED_TABLE_NAME", "")
                ref_col = fk.get("REFERENCED_COLUMN_NAME", "")
                lines.append(f"| `{constraint}` | `{col}` | `{ref_table}({ref_col})` |")

        lines.append("")

    return "\n".join(lines)
