"""Generates Markdown documentation for a database schema.
Supports MySQL, PostgreSQL and SQLite via db_service abstraction."""

from app.models.connection import Connection
from app.services import db_service


def generate_schema_markdown(conn: Connection, password: str | None, database: str) -> str:
    tables = db_service.list_tables(conn, password, database)

    all_columns: dict[str, list] = {}
    all_indexes: dict[str, list] = {}
    all_fks: dict[str, list] = {}

    for table in tables:
        name = table["TABLE_NAME"]
        detail = db_service.describe_table(conn, password, database, name)
        all_columns[name] = detail.get("columns", [])
        all_indexes[name] = detail.get("indexes", [])
        all_fks[name] = detail.get("foreign_keys", [])

    lines: list[str] = []
    lines.append(f"# Database Schema: `{database}`\n")
    lines.append(f"> Generated by WowDB · {len(tables)} table(s)\n")
    lines.append("---\n")

    lines.append("## Tables\n")
    lines.append("| Table | Engine | Approx. Rows | Comment |")
    lines.append("|---|---|---|---|")
    for t in tables:
        name = t.get("TABLE_NAME", "")
        engine = t.get("ENGINE", "—")
        rows = t.get("TABLE_ROWS", "—")
        comment = t.get("TABLE_COMMENT", "") or ""
        lines.append(f"| `{name}` | {engine} | {rows} | {comment} |")

    lines.append("")

    for t in tables:
        table_name = t.get("TABLE_NAME", "")
        lines.append(f"---\n\n## `{table_name}`\n")

        comment = (t.get("TABLE_COMMENT") or "").strip()
        if comment:
            lines.append(f"_{comment}_\n")

        lines.append("### Columns\n")
        lines.append("| Column | Type | Nullable | Key | Default | Extra |")
        lines.append("|---|---|---|---|---|---|")
        for col in all_columns.get(table_name, []):
            lines.append(
                f"| `{col.get('COLUMN_NAME', '')}` "
                f"| `{col.get('COLUMN_TYPE', '')}` "
                f"| {col.get('IS_NULLABLE', '')} "
                f"| {col.get('COLUMN_KEY', '') or '—'} "
                f"| {col.get('COLUMN_DEFAULT', '') or '—'} "
                f"| {col.get('EXTRA', '') or '—'} |"
            )

        indexes = all_indexes.get(table_name, [])
        if indexes:
            lines.append("\n### Indexes\n")
            lines.append("| Name | Unique | Column | Type |")
            lines.append("|---|---|---|---|")
            seen: set[str] = set()
            for idx in indexes:
                key = f"{idx.get('INDEX_NAME')}-{idx.get('COLUMN_NAME')}"
                if key in seen:
                    continue
                seen.add(key)
                unique = "No" if idx.get("NON_UNIQUE") else "Yes"
                lines.append(
                    f"| `{idx.get('INDEX_NAME', '')}` "
                    f"| {unique} "
                    f"| `{idx.get('COLUMN_NAME', '')}` "
                    f"| {idx.get('INDEX_TYPE', '')} |"
                )

        fks = all_fks.get(table_name, [])
        if fks:
            lines.append("\n### Foreign Keys\n")
            lines.append("| Constraint | Column | References |")
            lines.append("|---|---|---|")
            for fk in fks:
                lines.append(
                    f"| `{fk.get('CONSTRAINT_NAME', '')}` "
                    f"| `{fk.get('COLUMN_NAME', '')}` "
                    f"| `{fk.get('REFERENCED_TABLE_NAME', '')}({fk.get('REFERENCED_COLUMN_NAME', '')})` |"
                )

        lines.append("")

    return "\n".join(lines)
