"""Generates Markdown documentation for a MySQL database schema."""

from app.services.mysql_service import get_mysql_connection


def generate_schema_markdown(
    host: str, port: int, user: str, password: str, database: str
) -> str:
    with get_mysql_connection(host, port, user, password, database) as conn:
        with conn.cursor() as cur:
            # Tables overview
            cur.execute(
                "SELECT TABLE_NAME, ENGINE, TABLE_ROWS, TABLE_COMMENT "
                "FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME",
                (database,),
            )
            tables = [dict(r) for r in cur.fetchall()]

            # All columns for all tables in one query
            cur.execute(
                "SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, "
                "IS_NULLABLE, COLUMN_TYPE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA "
                "FROM information_schema.COLUMNS "
                "WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME, ORDINAL_POSITION",
                (database,),
            )
            all_columns: dict[str, list] = {}
            for row in cur.fetchall():
                all_columns.setdefault(row["TABLE_NAME"], []).append(dict(row))

            # All indexes in one query
            cur.execute(
                "SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, COLUMN_NAME, INDEX_TYPE "
                "FROM information_schema.STATISTICS "
                "WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX",
                (database,),
            )
            all_indexes: dict[str, list] = {}
            for row in cur.fetchall():
                all_indexes.setdefault(row["TABLE_NAME"], []).append(dict(row))

            # All foreign keys in one query
            cur.execute(
                "SELECT kcu.TABLE_NAME, kcu.CONSTRAINT_NAME, kcu.COLUMN_NAME, "
                "kcu.REFERENCED_TABLE_NAME, kcu.REFERENCED_COLUMN_NAME "
                "FROM information_schema.KEY_COLUMN_USAGE kcu "
                "JOIN information_schema.TABLE_CONSTRAINTS tc "
                "  ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME "
                "  AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA "
                "  AND kcu.TABLE_NAME = tc.TABLE_NAME "
                "WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY' AND kcu.TABLE_SCHEMA = %s",
                (database,),
            )
            all_fks: dict[str, list] = {}
            for row in cur.fetchall():
                all_fks.setdefault(row["TABLE_NAME"], []).append(dict(row))

    lines: list[str] = []
    lines.append(f"# Database Schema: `{database}`\n")
    lines.append(f"> Generated by WowDB · {len(tables)} table(s)\n")
    lines.append("---\n")

    lines.append("## Tables\n")
    lines.append("| Table | Engine | Approx. Rows | Comment |")
    lines.append("|---|---|---|---|")
    for t in tables:
        name = t.get("TABLE_NAME", "")
        engine = t.get("ENGINE", "—")
        rows = t.get("TABLE_ROWS", "—")
        comment = t.get("TABLE_COMMENT", "") or ""
        lines.append(f"| `{name}` | {engine} | {rows} | {comment} |")

    lines.append("")

    for t in tables:
        table_name = t.get("TABLE_NAME", "")
        lines.append(f"---\n\n## `{table_name}`\n")

        comment = (t.get("TABLE_COMMENT") or "").strip()
        if comment:
            lines.append(f"_{comment}_\n")

        # Columns
        lines.append("### Columns\n")
        lines.append("| Column | Type | Nullable | Key | Default | Extra |")
        lines.append("|---|---|---|---|---|---|")
        for col in all_columns.get(table_name, []):
            lines.append(
                f"| `{col.get('COLUMN_NAME', '')}` "
                f"| `{col.get('COLUMN_TYPE', '')}` "
                f"| {col.get('IS_NULLABLE', '')} "
                f"| {col.get('COLUMN_KEY', '') or '—'} "
                f"| {col.get('COLUMN_DEFAULT', '') or '—'} "
                f"| {col.get('EXTRA', '') or '—'} |"
            )

        # Indexes
        indexes = all_indexes.get(table_name, [])
        if indexes:
            lines.append("\n### Indexes\n")
            lines.append("| Name | Unique | Column | Type |")
            lines.append("|---|---|---|---|")
            seen: set[str] = set()
            for idx in indexes:
                key = f"{idx.get('INDEX_NAME')}-{idx.get('COLUMN_NAME')}"
                if key in seen:
                    continue
                seen.add(key)
                unique = "No" if idx.get("NON_UNIQUE") else "Yes"
                lines.append(
                    f"| `{idx.get('INDEX_NAME', '')}` "
                    f"| {unique} "
                    f"| `{idx.get('COLUMN_NAME', '')}` "
                    f"| {idx.get('INDEX_TYPE', '')} |"
                )

        # Foreign keys
        fks = all_fks.get(table_name, [])
        if fks:
            lines.append("\n### Foreign Keys\n")
            lines.append("| Constraint | Column | References |")
            lines.append("|---|---|---|")
            for fk in fks:
                lines.append(
                    f"| `{fk.get('CONSTRAINT_NAME', '')}` "
                    f"| `{fk.get('COLUMN_NAME', '')}` "
                    f"| `{fk.get('REFERENCED_TABLE_NAME', '')}({fk.get('REFERENCED_COLUMN_NAME', '')})` |"
                )

        lines.append("")

    return "\n".join(lines)
